{
 "title": "k8s(airflow) Resource Usage",
 "tags": [
  "kubernetes",
  "k8s",
  "usage",
  "resources",
  "system"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "bucket", "query": "buckets()" },
   {
    "name": "host",
    "label": "host",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"host\", start: -2d)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"pod_name\", start: -2d)"
   }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Per Node CPU Usage (all)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage_nanocores\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kubernetes_node\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000000 }))\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Per Node CPU Time (all)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kubernetes_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage_core_nanoseconds\")\n  |> group(columns: [\"node_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> difference(nonNegative: true)\n  |> yield(name: \"non_negative_difference\")"
    }
   ]
  },
  {
   "title": "Per Node CPU requests (all)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kubernetes_pod_container\")\n  |> filter(fn: (r) => r[\"_field\"] == \"resource_requests_millicpu_units\")\n  |> group(columns: [\"node_name\", \"pod_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({\n      node_name: r[\"node_name\"],\n      pod_name: r[\"pod_name\"],\n      requests: r[\"_value\"] / 1000.0\n  }))\n  |> yield(name: \"requests\")\n"
    }
   ]
  },
  {
   "title": "Per Node CPU limits (all)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kubernetes_pod_container\")\n  |> filter(fn: (r) => r[\"_field\"] == \"resource_limits_millicpu_units\")\n  |> group(columns: [\"node_name\", \"pod_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({ r with requests: r._value / 1000.0 }))\n  |> yield(name: \"requests\")\n"
    }
   ]
  },
  {
   "title": "Per Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kubernetes_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_usage_bytes\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({\n    r with _value: float(v: r._value)/ (1024.0 * 1024.0 * 1024.0)\n  }))\n  |> yield(name: \"max\") "
    }
   ]
  },
  {
   "title": "Per Node Memory (requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kubernetes_pod_container\")\n  |> filter(fn: (r) => r[\"_field\"] == \"resource_requests_memory_bytes\")\n  |> group(columns: [\"node_name\", \"pod_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"requests\")\n"
    }
   ]
  },
  {
   "title": "Per Total Node Memory (limits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kubernetes_pod_container\")\n  |> filter(fn: (r) => r[\"_field\"] == \"resource_requests_memory_bytes\")\n  |> group(columns: [\"node_name\", \"pod_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"requests\")\n"
    }
   ]
  },
  { "title": "Pod ($pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Restarts ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kubernetes_pod_container\")\n  |> filter(fn: (r) => r[\"_field\"] == \"restarts_total\")\n  |> filter(fn: (r) => r[\"namespace\"] == \"airflow\")\n  |> group(columns: [\"pod_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"restarts\")"
    }
   ]
  },
  {
   "title": "Pod CPU Usage ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Core" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"pod_name\"] == \"${pod}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage_nanocores\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kubernetes_pod_container\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000000 }))\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Pod CPU Time ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage_core_nanoseconds\")\n  |> filter(fn: (r) => r[\"pod_name\"] == \"${pod}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> difference(nonNegative: true)\n  |> yield(name: \"non_negative_difference\")"
    }
   ]
  },
  {
   "title": "Pod Memory Usage ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_usage_bytes\")\n  |> filter(fn: (r) => r[\"pod_name\"] == \"${pod}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({\n    r with _value: float(v: r._value)/ (1024.0 * 1024.0 * 1024.0)\n  }))\n  |> yield(name: \"max\") "
    }
   ]
  },
  {
   "title": "Pod Transmit Network ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"host\"] == \"${bucket}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kubernetes_pod_network\")\n  |> filter(fn: (r) => r[\"namespace\"] == \"airflow\" and r[\"pod_name\"] == \"${pod}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_bytes\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 })) \n  |> yield(name: \"tx_bytes\")\n"
    }
   ]
  },
  {
   "title": "Pod Receive Network ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kubernetes_pod_network\")\n  |> filter(fn: (r) => r[\"namespace\"] == \"airflow\" and r[\"pod_name\"] == \"${pod}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_bytes\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 })) \n  |> yield(name: \"rx_bytes\")\n"
    }
   ]
  }
 ]
}